"""
pytest plugin: generates docs/test_report.md after every test run.

The report is written atomically (write to a .tmp file, then os.replace) to
avoid leaving a half-written file if the process is killed. It replaces the
previous report entirely so it always reflects the current test state.
"""

from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

import pytest

# ---------------------------------------------------------------------------
# Internal state (module-level, reset per session via pytest_configure)
# ---------------------------------------------------------------------------

_results: List[Dict] = []
_session_start: str = ""


# ---------------------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------------------


def pytest_configure(config: pytest.Config) -> None:
    """Record session start time and reset results list."""
    global _session_start, _results
    _results = []
    _session_start = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    """Collect per-test outcome (call phase only; setup failures captured too)."""
    if report.when == "call" or (report.when == "setup" and report.outcome in ("failed", "error")):
        _results.append(
            {
                "nodeid": report.nodeid,
                "outcome": report.outcome,  # "passed", "failed", "error", "skipped"
                "duration": getattr(report, "duration", 0.0),
                "longrepr": str(report.longrepr) if report.failed else "",
            }
        )


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Write docs/test_report.md, replacing any previous version."""
    _write_report(exitstatus)


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------


def _outcome_badge(outcome: str) -> str:
    return {"passed": "PASS", "failed": "FAIL", "error": "ERROR", "skipped": "SKIP"}.get(
        outcome, outcome.upper()
    )


def _write_report(exitstatus: int) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    docs_dir = repo_root / "docs"
    report_path = docs_dir / "test_report.md"
    tmp_path = report_path.with_suffix(".md.tmp")

    passed = [r for r in _results if r["outcome"] == "passed"]
    failed = [r for r in _results if r["outcome"] == "failed"]
    errored = [r for r in _results if r["outcome"] == "error"]
    skipped = [r for r in _results if r["outcome"] == "skipped"]
    total = len(_results)
    end_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    overall = "ALL PASSED" if exitstatus == 0 else "FAILURES PRESENT"

    lines: List[str] = [
        "# Test Report",
        "",
        f"> Generated by `tests/conftest.py` on {end_time}. Replaced on every `pytest` run.",
        "",
        "## Summary",
        "",
        "| Started | Finished | Total | Passed | Failed | Errors | Skipped | Overall |",
        "|---------|----------|-------|--------|--------|--------|---------|---------|",
        f"| {_session_start} | {end_time} | {total} | {len(passed)} | {len(failed)} |"
        f" {len(errored)} | {len(skipped)} | **{overall}** |",
        "",
        "## Results by Test File",
        "",
    ]

    by_file: Dict[str, List[Dict]] = defaultdict(list)
    for r in _results:
        by_file[r["nodeid"].split("::")[0]].append(r)

    for file_path in sorted(by_file.keys()):
        tests = by_file[file_path]
        file_passed = sum(1 for t in tests if t["outcome"] == "passed")
        lines += [
            f"### `{file_path}` ({file_passed}/{len(tests)} passed)",
            "",
            "| Test | Result | Duration (s) |",
            "|------|--------|-------------|",
        ]
        for t in tests:
            name = t["nodeid"].split("::", 1)[-1] if "::" in t["nodeid"] else t["nodeid"]
            lines.append(f"| `{name}` | {_outcome_badge(t['outcome'])} | {t['duration']:.3f} |")
        lines.append("")

    failures = [r for r in _results if r["outcome"] in ("failed", "error")]
    if failures:
        lines += ["## Failure Details", ""]
        for r in failures:
            lines += [f"### `{r['nodeid']}`", "", "```", r["longrepr"][:4000], "```", ""]

    content = "\n".join(lines) + "\n"

    try:
        docs_dir.mkdir(parents=True, exist_ok=True)
        tmp_path.write_text(content, encoding="utf-8")
        os.replace(str(tmp_path), str(report_path))
    except OSError:
        # Non-fatal: a reporting failure must not break the test run itself.
        pass
